name: Build Console App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   # Replace with your target SDK version

      - name: Restore dependencies
        run: dotnet restore Aes67Receiver.slnx

      - name: Build and publish console app
        run: |
          dotnet publish ./Aes67AudioConsole/Aes67AudioConsole.csproj \
            -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true \
            -o out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aes67ConsoleApp-win-x64
          path: out/*.exe
